using System.CommandLine;
using System.Text.Json;
using Art.Common;

namespace Art.Tesler.Database;

public class DatabaseCommandList : DatabaseCommandBase
{
    protected Option<string> AugmentOption;

    protected Option<string> OutputOption;

    public DatabaseCommandList(
        IOutputControl toolOutput,
        ITeslerRegistrationProvider registrationProvider,
        string name,
        string? description = null)
        : base(toolOutput, registrationProvider, name, description)
    {
        AugmentOption = new Option<string>("--augment") { HelpName = "file", Description = "Use base profile file for profile generated by --output" };
        Add(AugmentOption);
        OutputOption = new Option<string>("-o", "--output") { HelpName = "file", Description = "Generate profile file" };
        Add(OutputOption);
    }

    protected override async Task<int> RunAsync(ParseResult parseResult, CancellationToken cancellationToken)
    {
        string? augment = parseResult.GetValue(AugmentOption);
        string? output = parseResult.GetValue(OutputOption);
        List<ArtifactKey>? selection = output != null ? new List<ArtifactKey>() : null;
        using var arm = RegistrationProvider.CreateArtifactRegistrationManager(parseResult);
        string? tool = parseResult.GetValue(ToolOption);
        string? group = parseResult.GetValue(GroupOption);
        string? toolLike = parseResult.GetValue(ToolLikeOption);
        string? groupLike = parseResult.GetValue(GroupLikeOption);
        string? id = parseResult.GetValue(IdOption);
        string? idLike = parseResult.GetValue(IdLikeOption);
        string? nameLike = parseResult.GetValue(NameLikeOption);
        IEnumerable<ArtifactInfo> en = (await arm.ListArtifactsOptionalsAsync(tool, group, cancellationToken: cancellationToken).ConfigureAwait(false)).WithFilters(tool, toolLike, group, groupLike, id, idLike, nameLike);
        bool listResource = parseResult.GetValue(ListResourceOption);
        bool detailed = parseResult.GetValue(DetailedOption);
        foreach (ArtifactInfo i in en)
        {
            await Common.DisplayAsync(i, listResource, arm, detailed, ToolOutput).ConfigureAwait(false);
            selection?.Add(i.Key);
        }
        if (output != null && selection != null)
        {
            Dictionary<ToolAndGroup, List<string>> dict = selection.GroupBy(x => new ToolAndGroup(x.Tool, x.Group)).ToDictionary(x => x.Key, x => x.Select(v => v.Id).ToList());
            List<ArtifactToolProfile> profiles = new();
            if (augment != null)
            {
                FileStream afs = File.OpenRead(augment);
                await using var afs1 = afs.ConfigureAwait(false);
                var augmentProfiles = ArtifactToolProfileUtil.DeserializeProfiles(afs);
                Dictionary<ToolAndGroup, ArtifactToolProfile> adict = augmentProfiles.ToDictionary(x => new ToolAndGroup(x.Tool, x.Group), x => x);
                foreach ((ToolAndGroup profile, List<string> value) in dict)
                    adict[profile] = adict.TryGetValue(profile, out ArtifactToolProfile? aprofile)
                        ? AugmentProfile(aprofile, value)
                        : CreateNewProfile(profile, value);
                profiles.AddRange(adict.Values);
            }
            else
            {
                foreach ((ToolAndGroup profile, List<string> value) in dict) profiles.Add(CreateNewProfile(profile, value));
            }
            FileStream fs = File.Create(output);
            await using var fs1 = fs.ConfigureAwait(false);
            await JsonSerializer.SerializeAsync(fs, profiles, SourceGenerationContext.s_context.ListArtifactToolProfile, cancellationToken).ConfigureAwait(false);
        }
        return 0;
    }

    private readonly record struct ToolAndGroup(string Tool, string? Group);

    private static ArtifactToolProfile AugmentProfile(ArtifactToolProfile profile, List<string> ids)
        => CreateNewProfile(new ToolAndGroup(profile.Tool, profile.Group), profile.Options != null ? new Dictionary<string, JsonElement>(profile.Options) : new Dictionary<string, JsonElement>(), ids);

    private static ArtifactToolProfile CreateNewProfile(ToolAndGroup profile, List<string> ids)
        => CreateNewProfile(profile, new Dictionary<string, JsonElement>(), ids);

    private static ArtifactToolProfile CreateNewProfile(ToolAndGroup profile, Dictionary<string, JsonElement> dict, List<string> ids)
    {
        dict["artifactList"] = JsonSerializer.SerializeToElement(ids, SourceGenerationContext.s_context.ListString);
        return new ArtifactToolProfile(profile.Tool, profile.Group, dict);
    }
}
