using System.CommandLine;
using System.Text.Json;
using Art.Common;

namespace Art.Tesler.Database;

public class DatabaseCommandList : DatabaseCommandBase
{
    protected Option<FileInfo> AugmentOption;

    protected Option<FileInfo> RefactoringsFileOption;

    protected Option<FileInfo> OutputOption;

    public DatabaseCommandList(
        IOutputControl toolOutput,
        ITeslerRegistrationProvider registrationProvider,
        string name,
        string? description = null)
        : base(toolOutput, registrationProvider, name, description)
    {
        AugmentOption = new Option<FileInfo>("--augment") { HelpName = "file", Description = "Use base profile file for profile generated by --output" };
        AugmentOption.AcceptExistingOnly();
        Add(AugmentOption);
        RefactoringsFileOption = new Option<FileInfo>("--refactorings-file") { HelpName = "file", Description = "Use this file to apply type or assembly refactorings" };
        RefactoringsFileOption.AcceptExistingOnly();
        Add(RefactoringsFileOption);
        OutputOption = new Option<FileInfo>("-o", "--output") { HelpName = "file", Description = "Generate profile file" };
        OutputOption.AcceptLegalFilePathsOnly();
        Add(OutputOption);
    }

    protected override async Task<int> RunAsync(ParseResult parseResult, CancellationToken cancellationToken)
    {
        FileInfo? augment = parseResult.GetValue(AugmentOption);
        FileInfo? refactoringsFile = parseResult.GetValue(RefactoringsFileOption);
        FileInfo? output = parseResult.GetValue(OutputOption);
        List<ArtifactKey>? selection = output != null ? [] : null;
        using var arm = RegistrationProvider.CreateArtifactRegistrationManager(parseResult, isReadonly: true);
        string? tool = parseResult.GetValue(ToolOption);
        string? group = parseResult.GetValue(GroupOption);
        string? toolLike = parseResult.GetValue(ToolLikeOption);
        string? groupLike = parseResult.GetValue(GroupLikeOption);
        string? id = parseResult.GetValue(IdOption);
        string? idLike = parseResult.GetValue(IdLikeOption);
        string? nameLike = parseResult.GetValue(NameLikeOption);
        Refactorings? refactorings = null;
        if (refactoringsFile != null)
        {
            await using (var afs = refactoringsFile.OpenRead())
            {
                refactorings = await JsonSerializer.DeserializeAsync(afs, SourceGenerationContext.s_context.Refactorings, cancellationToken);
            }
            if (refactorings == null)
            {
                throw new InvalidDataException($"Unexpected null JSON in {refactoringsFile.FullName}");
            }
        }
        IEnumerable<ArtifactInfo> en = (await arm.ListArtifactsOptionalsAsync(tool, group, cancellationToken: cancellationToken).ConfigureAwait(false)).WithFilters(tool, toolLike, group, groupLike, id, idLike, nameLike);
        bool listResource = parseResult.GetValue(ListResourceOption);
        bool detailed = parseResult.GetValue(DetailedOption);
        foreach (ArtifactInfo inputArtifactInfo in en)
        {
            ArtifactKey? refactoredKey = refactorings != null && refactorings.TryGetRefactoredArtifactKey(inputArtifactInfo.Key, out var tmpRefactoredKey) ? tmpRefactoredKey : null;
            ArtifactInfo finalArtifactInfo = refactoredKey != null ? inputArtifactInfo with { Key = refactoredKey } : inputArtifactInfo;
            await Common.DisplayAsync(inputArtifactInfo, listResource, arm, detailed, ToolOutput, refactoredKey).ConfigureAwait(false);
            selection?.Add(finalArtifactInfo.Key);
        }
        if (output != null && selection != null)
        {
            Dictionary<ToolAndGroup, List<string>> dict = selection.GroupBy(x => new ToolAndGroup(x.Tool, x.Group)).ToDictionary(x => x.Key, x => x.Select(v => v.Id).ToList());
            List<ArtifactToolProfile> profiles = [];
            if (augment != null)
            {
                ArtifactToolProfile[] augmentProfiles;
                await using (var augmentFs = augment.OpenRead())
                {
                    augmentProfiles = ArtifactToolProfileUtil.DeserializeProfiles(augmentFs);
                }
                Dictionary<ToolAndGroup, List<ArtifactToolProfile>> augmentDict = augmentProfiles
                    .GroupBy(static x => new ToolAndGroup(x.Tool, x.Group))
                    .ToDictionary(
                        static v => v.Key,
                        static x => x.ToList()
                    );
                foreach ((ToolAndGroup profile, List<ArtifactToolProfile> value) in augmentDict)
                {
                    profiles.AddRange(
                        dict.TryGetValue(profile, out List<string>? values)
                            ? value.Select(v => AugmentProfile(v, values))
                            : value
                    );
                }
                foreach ((ToolAndGroup profile, List<string> value) in dict)
                {
                    if (augmentDict.ContainsKey(profile))
                    {
                        continue;
                    }
                    profiles.Add(CreateNewProfile(profile, value));
                }
            }
            else
            {
                foreach ((ToolAndGroup profile, List<string> value) in dict)
                {
                    profiles.Add(CreateNewProfile(profile, value));
                }
            }
            await using var fs = output.Create();
            await JsonSerializer.SerializeAsync(fs, profiles, SourceGenerationContext.s_context.ListArtifactToolProfile, cancellationToken).ConfigureAwait(false);
        }
        return 0;
    }

    private readonly record struct ToolAndGroup(string Tool, string? Group);

    private static ArtifactToolProfile AugmentProfile(ArtifactToolProfile profile, List<string> ids)
        => CreateNewProfile(new ToolAndGroup(profile.Tool, profile.Group), profile.Options != null ? new Dictionary<string, JsonElement>(profile.Options) : new Dictionary<string, JsonElement>(), ids);

    private static ArtifactToolProfile CreateNewProfile(ToolAndGroup profile, List<string> ids)
        => CreateNewProfile(profile, new Dictionary<string, JsonElement>(), ids);

    private static ArtifactToolProfile CreateNewProfile(ToolAndGroup profile, Dictionary<string, JsonElement> dict, List<string> ids)
    {
        dict["artifactList"] = JsonSerializer.SerializeToElement(ids, SourceGenerationContext.s_context.ListString);
        return new ArtifactToolProfile(profile.Tool, profile.Group, dict);
    }
}
